- src/lstate.js
- src/lua.js
- src/lualib.js
Remove require of lualib.js from lua.js
> lualib: export various libraries

- src/defs.js
- src/lauxlib.js
- src/lbaselib.js
- src/ldebug.js
- src/ldo.js
- src/llex.js
- src/lobject.js
- src/lparser.js
- src/lstrlib.js
- src/ltablib.js
- src/lua.js
- src/luaconf.js
Moving things out of lobject.js that shouldn't be there
> Minor cleanups

- src/ldo.js
- src/llex.js
- src/ltm.js
This code now pushes JS errors as lightuserdata.
> Fix some errors I've run into while developing

- README.md
- src/lauxlib.js
- src/ldebug.js
- src/lfunc.js
- src/lobject.js
- src/lundump.js
- tests/tests.js
Found while working towards new table implementation
> Misc cleanups

- src/lapi.js
- src/ltablib.js
- src/lua.js
Almost a straight copy/paste from lua C sources.
Towards #1
> Use quicksort implementation from lua

- README.md
- src/liolib.js
Currently file objects are assumed to have an 'fd' member.
This is true for node's built in streams.
However node's built in streams assume everything is async, which is not a good match for lua's io library. This will probably have to change in future
Future things to watch out for:
- node's streams have no 'unget'
- node doesn't garbage collect files/fds (!!!)
> Flesh out io library a little

- src/ltable.js
Inspired by https://github.com/zloirock/core-js
> Optimized next

- README.md
- src/liolib.js
Just enough to get `io.output():flush()` to work
> Add a little more of IO library

- src/lapi.js
- src/lauxlib.js
- src/ldebug.js
- src/ldo.js
- src/lobject.js
- src/lparser.js
- src/lstate.js
- src/lstrlib.js
- src/luaconf.js
- src/lundump.js
- src/lvm.js
- tests/test-suite/errors.js
- tests/test-suite/events.js
- tests/test-suite/math.js
- tests/test-suite/nextvar.js
- tests/test-suite/strings.js
- yarn.lock
> Investigated + fixed some skipped tests

- src/lbaselib.js
> src/lbaselib.js: Print immediatly to console in node

- src/loadlib.js
- src/loslib.js
Fix use of node specific globals
> Tidy up for web

- README.md
- src/lapi.js
- src/lauxlib.js
- tests/lauxlib.js
> Fixes for luaL_ref (resolves #80)

- README.md
See also [#14](https://github.com/fengari-lua/fengari-web/pull/14)
> Getting started + JS API section

- src/loadlib.js
Various improvements for loading JS libraries in the browser.
Fixes #77
Closes #86
> In-browser loadlib improvements

- src/ldo.js
- src/llex.js
- src/llimits.js
- src/lmathlib.js
- src/lobject.js
- src/loslib.js
- src/lparser.js
- src/lstrlib.js
- src/ltablib.js
- src/luaconf.js
- src/lutf8lib.js
- src/lvm.js
Closes #1, lmathlib no longer requires llimit
> Moved LUA_MAX/MININTEGER from llimit.js to luaconf.js

- README.md
- src/lmathlib.js
- tests/test-suite/math.js
Uses same parameters as glibc in type 0 mode
Closes #78
> Implement math.randomseed via a simple LCG

- tests/test-suite/ltests.js
- Push copy of TValue to stack, not original
Fixes https://github.com/fengari-lua/fengari/commit/0d91aed9be2b4761e00d371410140c4b541eb14e#commitcomment-22312635
> ltests fixes

- .travis.yml
- src/luaconf.js
- webpack.config.js
> Add FENGARICONF variable to configure luaconf

- README.md
- src/fengarilib.js
- src/linit.js
- src/lualib.js
Alternative to #118
Closes https://github.com/fengari-lua/fengari-web/issues/13
> Add 'fengari' library containing version numbers etc

- .travis.yml
- NEWS
- src/lauxlib.js
- tests/lmathlib.js
- tests/load.js
Closes https://github.com/fengari-lua/fengari-node-cli/issues/5
> Node 6 compat

- src/lualib.js
> src/lualib.js: Add missing luaopen_base export

- src/lobject.js
- src/luaconf.js
> src/{luaconf,lobject}.js: Remove locale specific decimal point

- src/loslib.js
- test/loslib.test.js
As suggested in https://github.com/fengari-lua/fengari/issues/136#issuecomment-468902026 by @Egor-Skriptunoff
> src/loslib.js: implement os.setlocale

- src/lstrlib.js
> Remove String.repeat usage

- src/ltable.js
- test/lapi.test.js
There may be array indices higher than the map size.
Use `.size` as a starting point, not as a known high point
Fixes #162
> src/ltable.js: fix finding table length

- src/lstrlib.js
- test/lstrlib.test.js
> src/lstrlib.js: fix incorrect item calculation in push_captures
